### ISSUE TITLE
Game sorta crashes on world loading, all entities bugged (Alfheim is incompatible with Mixin)

### ISSUE THREAD

**Issue by 062regrahc** [DarkShadow44/SereneSeasons#9]
game freezes/crashes when a world is launched. player model cannot move and no entity models are visible
https://pastebin.com/1U5eW3hr
this is just one of the many reports the game generates, and all seem to have this problem in common
> java.lang.NoSuchMethodError: net.minecraft.block.Block.getRelativeSlipperiness(Lnet/minecraft/entity/Entity;)F

**Comment by DarkShadow44** [comment]
You're using the latest git version that you compiled yourself?

Must be some mod incompatibility, can you find out which one causes it?

**Comment by 062regrahc** [comment]
after testing out mods one-by-one, it turns out the Alfheim mod is the cause of the problem

**Comment by DarkShadow44** [comment]
Thanks, I'll look into it.

**Comment by DarkShadow44** [comment]
This is another instance of https://github.com/SpongePowered/Mixin/issues/24, although this is not a Mixin bug really.
The class transformer of Alfheim completely break when run multiple times. Since I use Mixin, this can happen. The only sensible approach here is to have the Alfheim  class transformers be repeatable. Not much I can do here, sorry.
